import React, { useState, useEffect, useCallback } from 'react';
import { generateOperaArticle } from '../services/aiClient';
import { Loader2, PenLine, CheckCircle2, AlertCircle, History, Trash2, Clock, Copy, Check, BookOpen, RefreshCw } from 'lucide-react';
import ReactMarkdown from 'react-markdown';
import { motion, AnimatePresence } from 'motion/react';
import { useAuth } from '../AuthContext';

const CATEGORIES = [
  'Entertainment', 'Politics', 'Lifestyle', 'Society', 'Sports', 'Technology', 'Business', 'Education'
];

interface Article {
  id: number;
  title: string;
  topic: string;
  category: string;
  content: string;
  image_url: string;
  created_at: string;
}

function extractTitle(markdown: string): { title: string; body: string } {
  const lines = markdown.split('\n');
  for (let i = 0; i < Math.min(5, lines.length); i++) {
    const match = lines[i].match(/^#{1,2}\s+(.+)$/);
    if (match) {
      const title = match[1].replace(/\*+/g, '').trim();
      const body = lines.slice(i + 1).join('\n').trimStart();
      return { title, body };
    }
  }
  return { title: '', body: markdown };
}

function readingTime(text: string): number {
  return Math.max(1, Math.ceil(text.split(/\s+/).length / 200));
}

function useElapsedTimer(active: boolean) {
  const [elapsed, setElapsed] = useState(0);
  useEffect(() => {
    if (!active) { setElapsed(0); return; }
    const id = setInterval(() => setElapsed(s => s + 1), 1000);
    return () => clearInterval(id);
  }, [active]);
  return elapsed;
}

function ArticleViewer({ content, image, topic, category }: {
  content: string;
  image: string;
  topic: string;
  category: string;
}) {
  const { title, body } = extractTitle(content);
  const mins = readingTime(content);
  const dateStr = new Date().toLocaleDateString('en-NG', { day: 'numeric', month: 'long', year: 'numeric' });
  const displayTitle = title || topic;

  return (
    <article className="max-w-2xl mx-auto font-sans">
      <div className="flex flex-wrap items-center gap-3 mb-5">
        <span className="bg-orange-600 text-white text-[11px] font-black uppercase tracking-widest px-3 py-1 rounded">
          {category}
        </span>
        <span className="flex items-center gap-1 text-neutral-400 text-xs font-medium">
          <BookOpen size={12} /> {mins} min read
        </span>
        <span className="flex items-center gap-1 text-neutral-400 text-xs font-medium">
          <Clock size={12} /> {dateStr}
        </span>
      </div>

      <h1 className="font-serif text-3xl sm:text-4xl font-black leading-tight text-neutral-900 mb-5" style={{ fontFamily: '"Playfair Display", serif' }}>
        {displayTitle}
      </h1>

      <div className="flex items-center gap-3 pb-5 mb-6 border-b border-neutral-200">
        <div className="w-9 h-9 rounded-full bg-orange-100 flex items-center justify-center text-orange-700 font-black text-sm flex-shrink-0">
          E
        </div>
        <div>
          <p className="text-sm font-bold text-neutral-800 leading-none mb-0.5">Emeka · All Hub AI Writer</p>
          <p className="text-xs text-neutral-400">{dateStr} · Opera News Hub</p>
        </div>
        <span className="ml-auto flex items-center gap-1.5 text-green-600 bg-green-50 border border-green-100 text-[10px] font-black uppercase tracking-widest px-2.5 py-1 rounded-full">
          <CheckCircle2 size={10} /> Hub Ready
        </span>
      </div>

      {image && (
        <figure className="mb-7">
          <div className="rounded-xl overflow-hidden shadow-lg border border-neutral-100 bg-neutral-100">
            <img
              src={image}
              alt={displayTitle}
              className="w-full aspect-video object-cover"
              referrerPolicy="no-referrer"
            />
          </div>
          <figcaption className="mt-2 text-center text-[11px] text-neutral-400 italic">
            Editorial image — {displayTitle}
          </figcaption>
        </figure>
      )}

      <div className="article-body">
        <ReactMarkdown>{body}</ReactMarkdown>
      </div>

      <div className="mt-8 pt-6 border-t border-neutral-200 flex items-center gap-2 text-neutral-400 text-xs">
        <CheckCircle2 size={13} className="text-green-500" />
        <span>Generated by All Hub · Optimised for Opera News Hub approval</span>
      </div>
    </article>
  );
}

export default function OperaWriter() {
  const [topic, setTopic] = useState('');
  const [category, setCategory] = useState(CATEGORIES[0]);
  const [loading, setLoading] = useState(false);
  const [content, setContent] = useState('');
  const [image, setImage] = useState('');
  const [headline, setHeadline] = useState('');
  const [imgPrompt, setImgPrompt] = useState('');
  const [copied, setCopied] = useState(false);
  const [error, setError] = useState('');
  const [history, setHistory] = useState<Article[]>([]);
  const [showHistory, setShowHistory] = useState(false);
  const { token } = useAuth();
  const elapsed = useElapsedTimer(loading);

  const authHeaders = token ? { Authorization: `Bearer ${token}` } : {};

  useEffect(() => {
    if (!token) return;
    fetch('/api/content/articles', { headers: authHeaders })
      .then(r => {
        if (!r.ok || !r.headers.get('content-type')?.includes('application/json')) return [];
        return r.json();
      })
      .then(data => Array.isArray(data) ? setHistory(data) : null)
      .catch(() => null);
  }, [token]);

  const saveArticle = async (articleContent: string, imageUrl: string) => {
    if (!token) return;
    try {
      const res = await fetch('/api/content/articles', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json', ...authHeaders },
        body: JSON.stringify({ title: topic, topic, category, content: articleContent, imageUrl })
      });
      if (res.ok) {
        const saved = await res.json();
        setHistory(prev => [saved, ...prev]);
      }
    } catch {
    }
  };

  const handleDelete = async (id: number) => {
    if (!token) return;
    await fetch(`/api/content/articles/${id}`, { method: 'DELETE', headers: authHeaders });
    setHistory(prev => prev.filter(a => a.id !== id));
  };

  const handleGenerate = useCallback(async () => {
    if (!topic.trim() || loading) return;
    setLoading(true);
    setError('');
    setContent('');
    setImage('');
    setHeadline('');
    setImgPrompt('');
    try {
      const data = await generateOperaArticle(topic, category);
      setContent(data.content || '');
      setImage(data.imageUrl || '');
      setHeadline(data.headline || '');
      setImgPrompt(data.image_generation_prompt || '');
      if (data.content) await saveArticle(data.content, data.imageUrl || '');
    } catch (err: any) {
      const msg = typeof err?.message === 'string' ? err.message : 'Failed to generate article. Please try again.';
      setError(msg);
    } finally {
      setLoading(false);
    }
  }, [topic, category, loading, token]);

  const handleCopy = () => {
    navigator.clipboard.writeText(content);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const loadingLabel = elapsed < 5
    ? 'Starting generation…'
    : elapsed < 20
    ? `Writing your article… (${elapsed}s)`
    : elapsed < 50
    ? `AI is crafting your content… (${elapsed}s)`
    : `Almost ready… (${elapsed}s)`;

  return (
    <div className="max-w-4xl mx-auto p-4 sm:p-6">

      {/* ── Writer Form ── */}
      <div className="bg-white rounded-2xl shadow-sm border border-neutral-100 p-6 sm:p-8 mb-8">
        <h2 className="text-2xl font-serif font-bold mb-1 flex items-center gap-2">
          <PenLine className="text-orange-600" />
          Opera News Hub AI Writer
        </h2>
        <p className="text-neutral-500 mb-6 text-sm">
          Writes like a human. Learns from real Nigerian news. Built to pass Opera's quality checks.
        </p>

        <div className="space-y-4">
          <div>
            <label className="block text-xs font-bold uppercase tracking-wider text-neutral-400 mb-1.5">
              Article Topic / Headline Idea
            </label>
            <input
              type="text"
              value={topic}
              onChange={(e) => setTopic(e.target.value)}
              onKeyDown={(e) => e.key === 'Enter' && handleGenerate()}
              placeholder="e.g. 5 Ways Nigerian Students Can Earn Online in 2026"
              className="w-full px-4 py-3 rounded-xl border border-neutral-200 focus:outline-none focus:ring-2 focus:ring-orange-500/20 transition-all text-sm"
              disabled={loading}
            />
          </div>

          <div>
            <label className="block text-xs font-bold uppercase tracking-wider text-neutral-400 mb-1.5">
              Category
            </label>
            <div className="flex flex-wrap gap-2">
              {CATEGORIES.map((cat) => (
                <button
                  key={cat}
                  onClick={() => setCategory(cat)}
                  disabled={loading}
                  className={`px-3 py-1.5 rounded-full text-xs font-semibold transition-all ${
                    category === cat
                      ? 'bg-orange-600 text-white shadow-md shadow-orange-200'
                      : 'bg-neutral-100 text-neutral-600 hover:bg-neutral-200'
                  } disabled:opacity-50`}
                >
                  {cat}
                </button>
              ))}
            </div>
          </div>

          <button
            onClick={handleGenerate}
            disabled={loading || !topic.trim()}
            className="w-full bg-neutral-900 text-white py-4 rounded-xl font-bold hover:bg-neutral-800 disabled:opacity-50 disabled:cursor-not-allowed transition-all flex items-center justify-center gap-2 text-sm"
          >
            {loading ? (
              <>
                <Loader2 className="animate-spin" size={18} />
                {loadingLabel}
              </>
            ) : (
              'Generate Pro Article'
            )}
          </button>
        </div>

        {/* Error state */}
        <AnimatePresence>
          {error && (
            <motion.div
              initial={{ opacity: 0, y: -8 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0 }}
              className="mt-4 p-4 bg-red-50 text-red-700 rounded-xl border border-red-100"
            >
              <div className="flex items-start gap-2 mb-3">
                <AlertCircle size={16} className="flex-shrink-0 mt-0.5" />
                <p className="text-sm font-medium leading-snug">{error}</p>
              </div>
              <button
                onClick={handleGenerate}
                disabled={loading || !topic.trim()}
                className="flex items-center gap-1.5 text-xs font-bold text-red-600 hover:text-red-800 bg-red-100 hover:bg-red-200 px-3 py-1.5 rounded-lg transition-all disabled:opacity-50"
              >
                <RefreshCw size={12} />
                Retry
              </button>
            </motion.div>
          )}
        </AnimatePresence>

        {/* ── Saved Articles ── */}
        {history.length > 0 && (
          <div className="mt-8 pt-6 border-t border-neutral-100">
            <button
              onClick={() => setShowHistory(!showHistory)}
              className="flex items-center gap-2 text-sm font-bold text-neutral-500 hover:text-neutral-900 transition-colors mb-4"
            >
              <History size={15} />
              {showHistory ? 'Hide Saved Articles' : `Saved Articles (${history.length})`}
            </button>

            <AnimatePresence>
              {showHistory && (
                <motion.div
                  initial={{ height: 0, opacity: 0 }}
                  animate={{ height: 'auto', opacity: 1 }}
                  exit={{ height: 0, opacity: 0 }}
                  className="overflow-hidden space-y-2"
                >
                  {history.map((item) => (
                    <div
                      key={item.id}
                      className="p-4 bg-neutral-50 rounded-xl border border-neutral-200 flex items-center justify-between group hover:border-orange-200 transition-colors"
                    >
                      <div
                        className="flex-1 cursor-pointer min-w-0"
                        onClick={() => {
                          setTopic(item.topic);
                          setCategory(item.category);
                          setContent(item.content);
                          setImage(item.image_url);
                          setTimeout(() => window.scrollTo({ top: 600, behavior: 'smooth' }), 50);
                        }}
                      >
                        <h4 className="font-semibold text-neutral-800 text-sm truncate">{item.title}</h4>
                        <div className="flex items-center gap-3 mt-1">
                          <span className="text-[10px] bg-orange-50 border border-orange-100 px-2 py-0.5 rounded text-orange-700 uppercase font-bold tracking-wider">{item.category}</span>
                          <span className="text-[10px] text-neutral-400 flex items-center gap-1 font-medium">
                            <Clock size={9} /> {new Date(item.created_at).toLocaleDateString()}
                          </span>
                        </div>
                      </div>
                      <button
                        onClick={() => handleDelete(item.id)}
                        className="p-2 ml-2 text-neutral-300 hover:text-red-500 hover:bg-red-50 rounded-lg transition-all opacity-0 group-hover:opacity-100 flex-shrink-0"
                      >
                        <Trash2 size={15} />
                      </button>
                    </div>
                  ))}
                </motion.div>
              )}
            </AnimatePresence>
          </div>
        )}
      </div>

      {/* ── Article Output ── */}
      <AnimatePresence>
        {content && (
          <motion.div
            initial={{ opacity: 0, y: 24 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.4 }}
            className="bg-white rounded-2xl shadow-sm border border-neutral-100 overflow-hidden"
          >
            <div className="flex items-center justify-between px-6 py-3 bg-neutral-50 border-b border-neutral-100">
              <span className="text-xs font-bold text-neutral-400 uppercase tracking-widest">Article Preview</span>
              <button
                onClick={handleCopy}
                className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-white border border-neutral-200 text-xs font-bold text-neutral-600 hover:bg-neutral-900 hover:text-white hover:border-neutral-900 transition-all"
              >
                {copied ? <Check size={13} /> : <Copy size={13} />}
                {copied ? 'Copied!' : 'Copy Article'}
              </button>
            </div>

            {headline && (
              <div className="px-6 sm:px-10 pt-6 pb-2 border-b border-neutral-100">
                <p className="text-[10px] font-bold uppercase tracking-widest text-orange-600 mb-1">AI Headline</p>
                <p className="text-sm font-bold text-neutral-900">{headline}</p>
              </div>
            )}

            <div className="p-6 sm:p-10">
              <ArticleViewer
                content={content}
                image={image}
                topic={topic}
                category={category}
              />
            </div>

            {imgPrompt && (
              <div className="px-6 sm:px-10 pb-6">
                <div className="bg-neutral-50 border border-neutral-100 rounded-xl p-4">
                  <p className="text-[10px] font-bold uppercase tracking-widest text-neutral-400 mb-2">Image Generation Prompt</p>
                  <p className="text-xs text-neutral-600 leading-relaxed">{imgPrompt}</p>
                  <button
                    onClick={() => { navigator.clipboard.writeText(imgPrompt); }}
                    className="mt-2 flex items-center gap-1.5 text-[10px] font-bold text-orange-600 hover:text-orange-700 transition-colors"
                  >
                    <Copy size={11} /> Copy Prompt
                  </button>
                </div>
              </div>
            )}
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}
